config/routes.rb
Rails.application.routes.draw do
  root to: "tops#index"
  resources :favorites, only: [:show, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :favorite
    end
  end
  resources :pictures do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image_pict, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image_user, ImageUploader
  has_secure_password
  has_many :pictures
  has_many :favorites, dependent: :destroy
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, on: :new
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.new(picture_params)
    @picture.image_pict.retrieve_from_cache! params[:cache][:image_pict]#carriewave確認設定
    if params[:back]
      render 'new'
    else
      if @picture.save
        SampleMailer.send_when_create(current_user).deliver
        redirect_to pictures_path, notice: "Pictureを作成しました！"
      else
        render 'new'
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "Pictureを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"Pictureを削除しました！"
  end

  def confirm
    @picture = current_user.pictures.new(picture_params)
    @picture.image_pict.cache!#carriewave一時的アップロード設定
    render :new if @picture.invalid?
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :content, :image_pict, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def authenticate_user
    unless current_user.id == @picture.user_id
      flash[:notice] = "ログインが必要"
      redirect_to new_session_path, notice:"ログインが必要です"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render 'new'
    else
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user.id), notice: "userを作成しました！"
      else
        render 'new'
      end
    end
  end

  def show
    @favorite = current_user.favorites
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "userを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice:"userを削除しました！"
  end

  def confirm
    @user = User.new(user_params)
    # @user.image_user.cache!#carriewave設定
    render :new if @user.invalid?
  end

  def favorite
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image_user)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authenticate_user
    unless current_user.id == @user.id
      flash[:notice] = "ログインが必要"
      redirect_to new_session_path, notice:"ログインが必要です"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header-menu">
      <div class="menu-box">
        <div class="nav navbar-nav">

          <% if logged_in? %>
          <ul>
            <li><%= link_to "#{current_user.name}", user_path(current_user.id) %></li>
            <li><%= link_to("Picture一覧","/pictures")%></li>
            <li><%= link_to("Picture投稿", new_picture_path) %></li>
            <li><%= link_to("ユーザー一覧", users_path) %></li>
            <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
          <% else %>
            <li><%= link_to("HOME", root_path, class: "rootLink") %></li>
            <li><%= link_to "ユーザー登録", new_user_path %></li>
            <li><%= link_to "ログイン", new_session_path %></li>
          </ul>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="w980">
  <%= form_with(model: @picture, url: choose_new_or_edit, local: true, html: { multipart: true } ) do |form| %>
    <div class="picture_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="picture_title">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="picture_title">
      <%= form.label :picture %>
      <%= form.file_field :image_pict %>
    </div>
    <%= form.submit %>
  <% end %>
</div>

app/views/pictures/confirm.html.erb
<div class="w980">
  <h3>以下の内容で、送信する。</h3>

  <%= form_with(model: @picture, url: pictures_path, local: true, html: { multipart: true }) do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%# キャッシュ名(一時ディレクトリの名前)をhiddenで渡す %>
    <%= hidden_field_tag :"cache[image_pict]", @picture.image_pict.cache_name %>

    <p>タイトル:<%= @picture.title %></p>
    <p>本文:<%= @picture.content %></p>
    <%# 一時ディレクトリの場所にある画像を表示 %>
    <%= image_tag(@picture.image_pict.url) %>
    <%= form.submit  "登録する" %>
    <%= form.submit "戻る", name: 'back'%>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<div class="w980">
  <h1>picture投稿編集</h1>
  <%= render 'form' %>
</div>

app/views/pictures/index.html.erb
<div class="w980">
  <h1>Picture一覧</h1>
  <p><%= notice %></p>
  <table>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
    </tr>

  <% @pictures.each do |picture| %>
    <tr>
      <td><%= picture.user.name %></td>
      <td><%= picture.title %></td>
      <td><%= picture.content %></td>
      <td><%= image_tag picture.image_pict.to_s %></td>
      <td><%= link_to '詳細を見る', picture_path(picture.id) %></td>
      <% if picture.user_id == current_user.id %>
        <td><%= link_to "編集する", edit_picture_path(picture.id) %></td>
        <td><%= link_to '削除する', picture_path(picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
      <% end %>
    </tr>
  <% end %>
  </table>
</div>

app/views/pictures/new.html.erb
<div class="w980">
  <h1>picture投稿</h1>
  <%= render 'form' %>
</div>

app/views/pictures/show.html.erb
<div class="w980">
  <h1>picture詳細画面</h1>
  <p>タイトル: <%= @picture.title %></p>
  <p>内容: <%= @picture.content %></p>
  <%= image_tag @picture.image_pict.to_s %>
  <p><%= @picture.user.name %></p>
  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

app/views/tops/index.html.erb
<div class="tops-wrap">
  <div class="tops-wrap-box">
    <div class="tops-bgimg">
    </div>
    <div class="tops-login">
      <h1 class="">Instagram</h1>
      <h2 class="">友達の写真や動画をチェックしよう</h2>
      <div class=""><div class=""></div><div class="">または</div><div class=""></div></div>
      <div class="">
        <%= form_with(model: @user, local: true) do |f| %>
          <%= f.text_field :name, placeholder: "名前" %>
          <%= f.email_field :email, placeholder: "E-mail" %>
          <%= f.password_field :password, placeholder: "パスワード" %>
          <%= f.password_field :password_confirmation, placeholder: "パスワード確認" %>
          <%= f.submit "ユーザー登録する" %>
        <% end %>
      </div>
      <div class=""><p class="">登録することで、Facebookの<a target="" href="https://help.instagram.com/581066165581870">利用規約</a>、<a target="_blank" href="https://help.instagram.com/519522125107875">データに関するポリシー</a>、<a target="_blank" href="/legal/cookies/">Cookieポリシー</a>に同意するものとします。</p></div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="w980">
  <h1>ユーザー情報編集</h1>
  <p><%= notice %></p>
  <%= form_with(model: @user, local: true ,url: user_path) do |form| %>
  <div class="user_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="user_title">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="user_title">
    <%= form.label :image_user %>
    <%= form.file_field :image_user %>
  </div>
  <%= form.submit %>
  <% end %>
</div>

app/views/users/favorite.html.erb
<div class="w980">
  <h1>お気に入り一覧</h1>
  <p><%= notice %></p>

  <% if @favorites.present? %>
    <P>お気に入りしているPicture</p>
      <table>
      <% @favorites.each do |favo| %>
      <tr>
        <td><%= favo.picture.user.name %></td>
        <td><%= favo.picture.title %></td>
        <td><%= image_tag favo.picture.image_pict.to_s %></td>
        <td><%= link_to '詳細を見る', picture_path(favo.picture.id) %></td>
      </tr><% end %>
      </table>
  <% else %>
    <P>お気に入りしているPictureはありません</p>
  <% end %>

</div>

app/views/users/index.html.erb
<div class="w980">
  <h1>user一覧</h1>
  <p><%= notice %></p>
  <table>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
    </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= image_tag user.image_user.to_s %></td>
      <td><%= link_to '詳細を見る', user_path(user.id) %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/users/new.html.erb
<div class="w980">
  <h1>Sign up</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "ユーザー登録する" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="w980">
  <h1>user詳細画面</h1>
  <p>タイトル: <%= @user.name %></p>
  <p>内容: <%= @user.email %></p>
  <%= image_tag @user.image_user.to_s %>
  <%= link_to "お気に入りリスト", favorite_user_path(@user.id) %>
  <% if @user.id == current_user.id %>
    <%= link_to "編集する", edit_user_path(@user.id) %>
    <%= link_to 'ユーザー削除', user_path(@user.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
<% end %>
</div>